### ISSUE TITLE
Records are only added from `Skyrim.esm`

### ISSUE THREAD

**Issue by radj307** [radj307/UniqueRegionNamesPatcher#2]
**Originally Reported By [mattski123](https://forums.nexusmods.com/index.php?/user/7571080-mattski123/)**

It seems to be bypassing records from later mods and only adding records from skyrim.esm ![](https://i.imgur.com/cUNLkzj.png) As you can see it's completely skipping landscape fixes for grass mods. Another example is Lanterns of Skyrim II here: ![](https://i.imgur.com/Ew6Zc5Y.png)

**Comment by radj307** [comment]
Related issue:  
https://github.com/Mutagen-Modding/Mutagen/issues/217

**Comment by mrudat** [comment]
Perhaps iterate over WinningContextOverrides for CELLs, rather than WRLDs? It doesn't appear that you use world, block or subblock in your logic, and Mutagen will handle copying the parent records as part of copying the context of the Cell.
