### ISSUE TITLE
Should this patch override or merge with the Unique Region Names.esp records?

### ISSUE THREAD

**Issue by darkrain261** [radj307/UniqueRegionNamesPatcher#6]
After running Synthesis, I checked and saw that there are records from this patch are overridden ones from the main mod esp, such as:
![1](https://github.com/radj307/UniqueRegionNamesPatcher/assets/103837232/fcc2d04d-d8f8-41bf-9d90-538fd2925648)

but there are also records that are merged like this: 
![2](https://github.com/radj307/UniqueRegionNamesPatcher/assets/103837232/82d4b59e-8c8b-4454-958e-c55c8b9f57ed)

Which one is intended and should I manually edit the patch? Thank you.

**Comment by radj307** [comment]
There's no need to manually edit the patch; the most likely problem with the record in the first image is that it was incorrectly tagged by the original mod.
